(function(){
  "use strict";
  const $=id=>document.getElementById(id),all=(s,r=document)=>Array.from(r.querySelectorAll(s));
  let client=null,session=null,data=null,current=null;
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const date=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';
  function toast(message,bad){const n=$('toast');n.textContent=message;n.classList.toggle('error',!!bad);n.hidden=false;clearTimeout(n._t);n._t=setTimeout(()=>n.hidden=true,bad?6000:3400);}
  async function rpc(name,args){const result=await client.rpc(name,args||{});if(result.error)throw result.error;return result.data;}
  function restoreSession(){try{session=JSON.parse(sessionStorage.getItem('amfcc_ops_session'));return !!session?.session_token;}catch(_){return false;}}
  function authorised(){return session&&(session.role==='management'||session.role==='administrator'||session.role==='department'&&session.department?.slug==='immigration');}
  async function load(){const result=await rpc('ops_immigration_bootstrap',{p_session_token:session.session_token});if(result.status!=='success')throw new Error(result.message||'Immigration records could not be loaded.');data=result;render();}
  function render(){const s=data.summary||{};$('access-label').textContent=(session.display_name||'Immigration')+' · '+(data.can_edit?'Edit access':'Read-only access');$('read-only-banner').hidden=data.can_edit;$('summary-cards').innerHTML=[[s.total||0,'Active students'],[s.local||0,'Local'],[s.international||0,'International'],[s.not_recorded||0,'Not recorded'],[s.passports_expiring_90_days||0,'Passports ≤90 days'],[s.permits_expiring_90_days||0,'Permits ≤90 days']].map(x=>'<article class="summary-card"><span class="label">'+x[1]+'</span><span class="value">'+x[0]+'</span></article>').join('');
    const countries=Array.from(new Set((data.students||[]).map(s=>s.country).filter(Boolean))).sort();$('country-filter').innerHTML='<option value="all">All countries</option>'+countries.map(c=>'<option>'+esc(c)+'</option>').join('');renderRows();}
  function expiryState(value){if(!value)return'';const days=(new Date(value+'T12:00:00')-new Date())/86400000;if(days<0)return'expired';if(days<=90)return'warning';return'';}
  function attentionMatch(s,filter){if(filter==='all')return true;if(filter==='missing_passport')return!s.passport_number;if(filter==='has_documents')return(s.documents||[]).length>0;const dates=[s.passport_expiry_date,s.permit_expiry_date].filter(Boolean),now=new Date();if(filter==='expired')return dates.some(d=>new Date(d+'T12:00:00')<now);if(filter==='expiring')return dates.some(d=>{const days=(new Date(d+'T12:00:00')-now)/86400000;return days>=0&&days<=90;});return true;}
  function renderRows(){const q=$('search').value.trim().toLowerCase(),status=$('status-filter').value,country=$('country-filter').value,attention=$('attention-filter').value;const rows=(data.students||[]).filter(s=>(status==='all'||s.residency_status===status)&&(country==='all'||s.country===country)&&attentionMatch(s,attention)&&(`${s.student_name} ${s.registration_number} ${s.country||''} ${s.nationality||''} ${s.sponsor_name||''}`.toLowerCase().includes(q)));$('student-rows').innerHTML=rows.length?rows.map(s=>'<tr><td class="student-cell"><strong>'+esc(s.student_name)+'</strong><small>'+esc(s.registration_number)+'</small></td><td><span class="residency-pill '+esc(s.residency_status)+'">'+esc(s.residency_status==='local'?'Local':s.residency_status==='international'?'International':'Not recorded')+'</span></td><td>'+esc(s.country||'—')+'</td><td>'+esc(s.sponsor_name||'—')+'<br><small>'+esc(s.sponsor_phone||'')+'</small></td><td>'+esc(s.passport_number||'—')+'<br><small class="expiry-note '+expiryState(s.passport_expiry_date)+'">'+(s.passport_expiry_date?'Expires '+date(s.passport_expiry_date):'')+'</small></td><td>'+esc(s.permit_type||'—')+'<br><small class="expiry-note '+expiryState(s.permit_expiry_date)+'">'+(s.permit_expiry_date?'Expires '+date(s.permit_expiry_date):'')+'</small></td><td>'+esc(s.residence||'—')+(s.room?'<br><small>Room '+esc(s.room)+'</small>':'')+'</td><td><button class="button secondary compact" data-student="'+esc(s.student_id)+'">View</button></td></tr>').join(''):'<tr><td colspan="8" class="empty-state">No matching students.</td></tr>';all('[data-student]').forEach(b=>b.onclick=()=>openRecord(b.dataset.student));}
  function set(id,value){$(id).value=value==null?'':value;}
  function openRecord(id){current=(data.students||[]).find(s=>s.student_id===id);if(!current)return;$('student-name').textContent=current.student_name;$('student-meta').textContent='Registration '+current.registration_number+' · '+(current.gender||'Gender not recorded');set('residency-status',current.residency_status==='international'?'international':'local');set('country',current.country);set('nationality',current.nationality);set('accommodation',[current.residence,current.room&&'Room '+current.room].filter(Boolean).join(' · ')||'Not allocated');set('passport-number',current.passport_number);set('passport-issue',current.passport_issue_date);set('passport-expiry',current.passport_expiry_date);set('permit-type',current.permit_type);set('permit-number',current.permit_number);set('permit-issue',current.permit_issue_date);set('permit-expiry',current.permit_expiry_date);set('sponsor-name',current.sponsor_name);set('sponsor-phone',current.sponsor_phone);set('sponsor-email','');set('sponsor-relationship','');set('sponsor-address','');set('sponsor-notes','');set('next-action',current.next_action);set('next-action-date',current.next_action_date);set('notes',current.notes);set('actor-name',localStorage.getItem('amfcc_immigration_actor')||current.updated_by||'');toggleInternational();renderDocuments();$('profile-form').classList.toggle('readonly',!data.can_edit);$('document-section').classList.toggle('readonly',!data.can_edit);all('#profile-form input,#profile-form select,#profile-form textarea').forEach(n=>{if(n.id!=='accommodation')n.disabled=!data.can_edit;});$('record-modal').hidden=false;}
  function closeRecord(){$('record-modal').hidden=true;current=null;}
  function toggleInternational(){const international=$('residency-status').value==='international';all('.international-field').forEach(n=>n.hidden=!international);$('country').required=international;}
  function renderDocuments(){$('document-list').innerHTML=(current.documents||[]).map(d=>'<div class="document-row"><span><strong>'+esc(d.document_type)+'</strong><br><small>'+esc(d.file_name)+' · '+date(d.uploaded_at)+'</small></span><div class="document-actions"><button class="button secondary compact" data-download="'+d.id+'">Open</button>'+(data.can_edit?'<button class="button warning compact" data-delete="'+d.id+'">Delete</button>':'')+'</div></div>').join('')||'<p class="muted">No immigration documents uploaded.</p>';all('[data-download]').forEach(b=>b.onclick=()=>documentAction('signed_url',b.dataset.download));all('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this private document?'))documentAction('delete',b.dataset.delete);});}
  async function edge(body){const response=await fetch(APP_CONFIG.SUPABASE_URL+'/functions/v1/immigration-documents',{method:'POST',headers:{'Content-Type':'application/json','apikey':APP_CONFIG.SUPABASE_PUBLISHABLE_KEY,'Authorization':'Bearer '+APP_CONFIG.SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify(Object.assign({session_type:'ops',session_token:session.session_token},body))});const result=await response.json();if(!response.ok||result.status!=='success')throw new Error(result.message||'Document request failed.');return result;}
  async function documentAction(action,id){try{const result=await edge({action:action,document_id:id,student_id:current.student_id});if(action==='signed_url')window.open(result.signed_url,'_blank','noopener');else{toast('Document deleted.');await load();openRecord(current.student_id);}}catch(error){toast(error.message,true);}}
  async function saveProfile(event){event.preventDefault();const button=$('save-profile'),label=button.textContent;button.disabled=true;button.textContent='Saving…';try{const actor=$('actor-name').value.trim();if(!actor)throw new Error('Enter your name for the audit record.');localStorage.setItem('amfcc_immigration_actor',actor);let sponsorId=current.sponsor_id||null;const sponsorName=$('sponsor-name').value.trim(),sponsorPhone=$('sponsor-phone').value.trim();if(sponsorName||sponsorPhone){const sr=await rpc('ops_immigration_save_sponsor',{p_session_token:session.session_token,p_student_id:current.student_id,p_sponsor:{name:sponsorName,phone:sponsorPhone,email:$('sponsor-email').value.trim(),relationship:$('sponsor-relationship').value.trim(),address:$('sponsor-address').value.trim(),notes:$('sponsor-notes').value.trim()},p_actor_name:actor});if(sr.status!=='success')throw new Error(sr.message);sponsorId=sr.sponsor_id;}
      const profile={residency_status:$('residency-status').value,country:$('country').value.trim(),nationality:$('nationality').value.trim(),sponsor_id:sponsorId,passport_number:$('passport-number').value.trim(),passport_issue_date:$('passport-issue').value,passport_expiry_date:$('passport-expiry').value,permit_type:$('permit-type').value.trim(),permit_number:$('permit-number').value.trim(),permit_issue_date:$('permit-issue').value,permit_expiry_date:$('permit-expiry').value,next_action:$('next-action').value.trim(),next_action_date:$('next-action-date').value,notes:$('notes').value.trim()};const result=await rpc('ops_immigration_save_profile',{p_session_token:session.session_token,p_student_id:current.student_id,p_profile:profile,p_actor_name:actor});if(result.status!=='success')throw new Error(result.message);toast(result.message);const id=current.student_id;await load();openRecord(id);
    }catch(error){toast(error.message||'Record could not be saved.',true);}finally{button.disabled=false;button.textContent=label;}}
  async function upload(event){event.preventDefault();const file=$('document-file').files[0];if(!file)return;if(file.size>10485760)return toast('The document must be no larger than 10 MB.',true);const button=event.currentTarget.querySelector('button'),label=button.textContent;button.disabled=true;button.textContent='Uploading…';try{const prep=await edge({action:'prepare_upload',student_id:current.student_id,file_name:file.name,document_type:$('document-type').value,mime_type:file.type,file_size:file.size});const upload=await client.storage.from(prep.bucket).uploadToSignedUrl(prep.storage_path,prep.upload_token,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;await edge({action:'confirm_upload',student_id:current.student_id,document_id:prep.document_id});toast('Private document uploaded.');const id=current.student_id;await load();openRecord(id);event.currentTarget.reset();}catch(error){toast(error.message||'Upload failed.',true);}finally{button.disabled=false;button.textContent=label;}}
  function bind(){['search','status-filter','country-filter','attention-filter'].forEach(id=>$(id).addEventListener('input',renderRows));$('refresh-button').onclick=()=>load().then(()=>toast('Immigration records refreshed.')).catch(e=>toast(e.message,true));$('close-modal').onclick=closeRecord;$('record-modal').onclick=e=>{if(e.target===$('record-modal'))closeRecord();};$('residency-status').onchange=toggleInternational;$('profile-form').onsubmit=saveProfile;$('upload-form').onsubmit=upload;}
  document.addEventListener('DOMContentLoaded',async()=>{if(!restoreSession()||!authorised()){location.replace('index.html');return;}client=window.supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});bind();try{await load();}catch(error){toast(error.message||'Immigration records could not be loaded.',true);}});
})();
